### PR TITLE
Making Georgs removal

### PR DESCRIPTION
**Pull request by ArturAkh**

### CODE REVIEW

**Comment by ArturAkh** [comment]
Why does Travis fail due to this simple removal?

**Comment by ArturAkh** [comment]
Should I revert the merge?

**Comment by fcolombo** [comment]
It might be that the test is failing because you merged this pull request before the test was done. Let's see what the test says on the KappaTools master branch

**Comment by ArturAkh** [comment]
ok

**Comment by fcolombo** [comment]
The tests are fine on the master branch

**Pull request merged**
