### PR TITLE
Compile KappaTools with scram/cmake

### PR DESCRIPTION
**Pull request by thomas-mueller**
I changed the KappaTools directory structure such that it is now possible to compile it with scram (successfully tested in the Higgs analysis) and with cmake (successfully tested in the Z+jet analysis).

### CODE REVIEW

**Comment by claria** [comment]
Hi,

i assume it works for the the htt and the excalibur code. Are there any further objections to merge this, @FredStober or can we push it into the master?

**Comment by FredStober** [comment]
Squash d02609e into 6884942 before merging

**Comment by thomas-mueller** [comment]
Hi Fred, maybe I do not understand what you mean, but do you want us to change the history of commits??? Cheers, Thomas

**Comment by FredStober** [comment]
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history - yes, its still your "personal" branch, right?

**Comment by thomas-mueller** [comment]
Thanks for explaining us the need of having these commits squashed.

**Comment by FredStober** [comment]
This is a typical case of A changed to B changed to C. It helps to keep the history understandable, if such iterations in a private branch stay private and don't enter the history of the "master" branch.
The whole branch should probably also get rebased onto the current master.

**Comment by claria** [comment]
Hi,
i won't squash these two commits since the b38fe5c commit in between, in which old plotting code was removed, makes the interactive rebasing fail and i am too lazy to fix it by hand..

**Comment by thomas-mueller** [comment]
In order to compile KappaTools with scram, you need to source the ini script or manually execute [this line](https://github.com/KappaAnalysis/KappaTools/blob/master/Toolbox/scripts/ini_KappaTools.sh#L11).

**Comment by claria** [comment]
Not anymore.

**Pull request merged**
